# TODO:
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-cert
spec:
  secretName: tls-cert
  issuerRef:
    name: ca-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048