apiVersion: v1
kind: Service
metadata:
  labels:
    app: generator-rust-server
  name: generator-rust-server
spec:
  ports:
  {{- if .Values.ssl.enabled }}
  - port: 4433
    protocol: TCP
    targetPort: 4433
  {{- else }}
  - port: 9090
    protocol: TCP
    targetPort: 9090
  {{- end }}
  selector:
    app: generator-rust-server
  sessionAffinity: None
  type: NodePort