apiVersion: v1
kind: Service
metadata:
  labels:
    app: generator-rust-server
  name: generator-rust-server
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: generator-rust-server
  sessionAffinity: None
  type: ClusterIP